### ISSUE TITLE
Minor Issue:   translator.onTranslatedLanguage has not been initialised

### ISSUE THREAD

**Issue by Hasankanso** [channdara/flutter_translator#2]
Hello there,
thanks for the awesome package, It's simple and very intuitive.

I suggest an enhancement, in my case I don't want to assign a method to onTrasnlatedLanguage callback, but I get a runtime error when it's null.

I had to add this line :  `translator.onTranslatedLanguage = (locale) => {};` to remove the error,
I suggest to check if onTranslateLanguage is not equal to null, and then call it

**Comment by channdara** [comment]
@Hasankanso 
Hello. Thank you for your suggestion. I will add this to the package soon as possible.
